### ISSUE TITLE
[1.4.2] Editor not loading. [Warning:ShortMenuLoader] Worker task failed due to an unexpected error!

### ISSUE THREAD

**Issue by TokcDK** [krypto5863/COM3D2.ShortMenuLoader#2]
Still cant load editor with version 1.4+, with v1.3 editor loading with no problems.

Just attached log where is all errors before closed console.
[LogOutput.zip](https://github.com/krypto5863/COM3D2.ShortMenuLoader/files/7204009/LogOutput.zip)

Tried to set "Time Between Breaks in Seconds" parameter to 15 and result was quite same then set it to 60 and was couple "Worker task failed" warnings and .mod errors disappeared but editor still not loaded.

Have game and mod files on hdd. Mod files size is about 70gb. With SMLv1.3 after loading editor process of game consumes about 6gb. ram.

**Comment by krypto5863** [comment]
Time between breaks is unrelated here. The very last version of SML was targeting this issue. This seems to be an issue mostly with exceptionally slow hard-drives or CPUs, they require more time before timing out, a value I moved up to 5 seconds before a timeout and apparently... somehow... was too low.

Try that, I've pushed the default timeout by double and added an option in the config incase that isn't enough, you can increase it manually

[ShortMenuLoader.Plugin.zip](https://github.com/krypto5863/COM3D2.ShortMenuLoader/files/7204730/ShortMenuLoader.Plugin.zip)

**Comment by TokcDK** [comment]
Tested attached version. In my case with 20000 still was mutex fail message and editor loaded only when set it to 30000.

**Comment by krypto5863** [comment]
Wow that's a wild amount of time to wait for a file to be read... If you could tell me your system specs and send a log of a successful entry into edit mode, wanna confirm no errors are cropping up before I push the new version. Please send the output_log.txt in COM3d2x64_data

**Comment by TokcDK** [comment]
There slow reading because it is hdd and it has 3 parts and game on third part and there only 11gb of free space from 1tb. 200gb of fragmented files placed in third slowest part of 3tb hdd and so timings in the result.
Here is fragment of log from start to finish of editor loading (time with made cache and without cache time is x2):
[editorLoadLog.zip](https://github.com/krypto5863/COM3D2.ShortMenuLoader/files/7218354/editorLoadLog.zip)

**Comment by krypto5863** [comment]
Primary issue is the .mod format for mods is also trash. It's slow, limited and replaced by .menu, .mates, etc,. Anyways thanks for information, I'll push the default timeout limit to 50 seconds (which is a fuck load) and that should resolve the issue for most everyone.
