### ISSUE TITLE
Male heads on maid edit mode

### ISSUE THREAD

**Issue by Gitubhu** [krypto5863/COM3D2.ShortMenuLoader#3]
ShortMenuLoader causes male heads to appear on maid edit mode, if you click on one of the male heads the game gets almost blocked
SML installed
![1](https://user-images.githubusercontent.com/37759562/146921302-142bbd25-20a7-4038-bb0c-dd73cfed0e04.png)
SML not installed
![2](https://user-images.githubusercontent.com/37759562/146921466-ba6ac311-d692-4823-85fc-4d1ea0e60ac4.png)

**Comment by krypto5863** [comment]
SML does not support the 3.0/CR-Edit branch of COM. I'll be sure to add this info in the description.
